apiVersion: v1
kind: Secret
metadata:
  name: autoscale-hub-secrets
  labels:
    app: autoscale-hub
type: Opaque
stringData:
  DB_USER: "autoscale_admin"
  DB_PASSWORD: "SuperSecurePassword123!"
  API_KEY: "ash-prod-secret-token"
